### ISSUE TITLE
Governance promo video

### ISSUE THREAD

**Issue by deadthings** [zocteam/website#8]
Would like to integrate this video into the website somewhere... https://youtu.be/HTMAkn7R6mE

**Comment by OwenRay** [comment]
video is unavailable
![image](https://user-images.githubusercontent.com/971553/57968357-916ede80-7969-11e9-9912-eff098b3b222.png)

**Comment by deadthings** [comment]
Can alternatively be grabbed from here: https://mega.nz/#!2xkEhaxA!NmNRxug-bGvQXxfvo2WjtptBMqU0ZafcnyBQpg0z4Z8
